#ifndef DEDICATED_GAME_SERVER_BASE
#define DEDICATED_GAME_SERVER_BASE

#include <shared/shared.h>

#define BEGIN_DGS_NAMESPACE namespace dgs {
#define END_DGS_NAMESPACE }

BEGIN_DGS_NAMESPACE

END_DGS_NAMESPACE

#endif // DEDICATED_GAME_SERVER_BASE