#ifndef SHARED_NETWORK_BASE
#define SHARED_NETWORK_BASE

#include "shared/shared_base.h"

BEGIN_SHARED_NAMESPACE

#define BEGIN_NETWORK_NAMESPACE namespace network {
#define END_NETWORK_NAMESPACE }

BEGIN_NETWORK_NAMESPACE

END_NETWORK_NAMESPACE

END_SHARED_NAMESPACE

#endif // SHARED_NETWORK_BASE