#ifndef SHARED_ONLINE_BASE
#define SHARED_ONLINE_BASE

#include "shared/shared_base.h"

BEGIN_SHARED_NAMESPACE

#define BEGIN_ONLINE_NAMESPACE namespace online {
#define END_ONLINE_NAMESPACE }

BEGIN_ONLINE_NAMESPACE

END_ONLINE_NAMESPACE

END_SHARED_NAMESPACE

#endif // SHARED_ONLINE_BASE