#ifndef HERMES_SYSTEM_BASE
#define HERMES_SYSTEM_BASE

#include "hermes/hermes_base.h"

BEGIN_HERMES_NAMESPACE

#define BEGIN_SYSTEM_NAMESPACE namespace system {
#define END_SYSTEM_NAMESPACE }

BEGIN_SYSTEM_NAMESPACE

END_SYSTEM_NAMESPACE

END_HERMES_NAMESPACE

#endif // HERMES_SYSTEM_BASE